### ----- General ----- ###
GENERAL:
  NAME: 'SpikingRTNH_s1_t5_l3_infer_s1to3_gradual0p9'
  COMMENT1: '0~72, -16~16, -2~7.6'
  VERSION: '2.0'
  SEED: 20250128
  IS_CUDA_SEED: True
  IS_DETERMINISTIC: True
  DEVICE: 'gpu'
  RESUME:
    IS_RESUME: False
    PATH_EXP: # None
    START_EP: # None
    IS_COPY_LOGS: True

  LOGGING:
    IS_LOGGING: True
    PATH_LOGGING: './logs'
    IS_SAVE_MODEL: True
    INTERVAL_EPOCH_MODEL: 1
    INTERVAL_EPOCH_UTIL: 5
is_validation_updated: True
### ----- General ----- ###

### ----- Dataset ----- ###
cfg_dataset_ver2: True
get_loss_from: 'detector'
DATASET:
  NAME: 'KRadarDetection_v2_0'

  NUM: # Total number of frames, just make this blank

  path_data:
    list_dir_kradar: ['/media/oem/HDD_8TB/kradar_dataset/generated_files']
    split: ['./resources/split/train.txt', './resources/split/test.txt']
    revised_label_v1_1: './tools/revise_label/kradar_revised_label_v1_1'
    revised_label_v2_0: './tools/revise_label/kradar_revised_label_v2_0/KRadar_refined_label_by_UWIPL'
    revised_label_v2_1: './tools/revise_label/kradar_revised_label_v2_1/KRadar_revised_visibility'
  label_version: 'v2_0'
  item: {
    'calib': True,
    'ldr64': False,
    'ldr128': False,
    'rdr': False,
    'rdr_sparse': True,
    'cam': False,
  }
  calib: {
    'z_offset': 0.7
  }
  ldr64: {
    'processed': False,
    'skip_line': 13,
    'n_attr': 9,
    'inside_ldr64': True,
    'calib': True,
  }
  rdr: {
    'cube': False,
  }
  rdr_sparse: {
    'processed': True,
    'dir': '/media/oem/HDD_8TB/rdr_sparse_data/rtnh_wider_1p_1'
  }
  roi: {
    'filter': True,
    'xyz': [0.,-16.,-2.,72.,16.,7.6],
    'keys': ['rdr_sparse'],
    'check_azimuth_for_rdr': True,
    'azimuth_deg': [-53,53],
    'grid_size': 0.4,
    'voxel_size': [0.4, 0.4, 0.4], # xyz
  }
  label: { # (consider, logit_idx, rgb, bgr)
    'calib':            True,
    'onlyR':            False,
    'consider_cls':     True,
    'consider_roi':     True,
    'remove_0_obj':     True,
    'Sedan':            [True,  1,  [0, 1, 0],       [0,255,0]],
    'Bus or Truck':     [True,  2,  [1, 0.2, 0],     [0,50,255]],
    'Motorcycle':       [False, -1, [1, 0, 0],       [0,0,255]],
    'Bicycle':          [False, -1, [1, 1, 0],       [0,255,255]],
    'Bicycle Group':    [False, -1, [0, 0.5, 1],     [0,128,255]],
    'Pedestrian':       [False, -1, [0, 0, 1],       [255,0,0]],
    'Pedestrian Group': [False, -1, [0.4, 0, 1],     [255,0,100]],
    'Label':            [False, -1, [0.5, 0.5, 0.5], [128,128,128]],
  }
  collate_fn: 'v2_0'
  load_from_pickle: './pkl'
### ----- Dataset ----- ###

### ----- Model ----- ###
MODEL:
  NAME: 'SpikingRTNH'
  SKELETON: 'SpikingRTNH'
  
  SPIKING:
    STEP: 3
    TEMP: 5.0

    GRADUAL_SPIKING:
      IS_GRADUAL: True
      PORTION: 0.9

  PRE_PROCESSOR:
    INPUT_DIM: 4 # in [4, 5] / 5 for Doppler

  BACKBONE:
    USE_3_LAYER: True
    ENCODING:
      CHANNEL: [64, 128, 256]
      STRIDE:  [1, 2, 2]
      PADDING: [1, 1, 1]
    TO_BEV:
      IS_Z_EMBED: False
      CHANNEL: [256, 256, 256]
      KERNEL_SIZE: [3, 6, 12]
      STRIDE:  [1, 2, 4]
      PADDING: [1, 2, 4]
  
  HEAD:
    NAME: 'AnchorHeadSingle'
    INPUT_CHANNELS: 768
    CLASS_AGNOSTIC: False

    USE_DIRECTION_CLASSIFIER: True
    DIR_OFFSET: 0.78539
    DIR_LIMIT_OFFSET: 0.0
    NUM_DIR_BINS: 2

    ANCHOR_GENERATOR_CONFIG: [
      {
          'class_name': 'Sedan',
          'anchor_sizes': [[4.2, 2.1, 2.0]],
          'anchor_rotations': [0, 1.57],
          'anchor_bottom_heights': [-1.08],
          'align_center': False,
          'feature_map_stride': 1,
          'matched_threshold': 0.5,
          'unmatched_threshold': 0.2
      },
      {
          'class_name': 'Bus or Truck',
          'anchor_sizes': [[9.5, 3.2, 3.7]],
          'anchor_rotations': [0, 1.57],
          'anchor_bottom_heights': [-1.08],
          'align_center': False,
          'feature_map_stride': 1,
          'matched_threshold': 0.45,
          'unmatched_threshold': 0.15
      },
    ]
    
    TARGET_ASSIGNER_CONFIG:
      NAME: AxisAlignedTargetAssigner
      POS_FRACTION: -1.0
      SAMPLE_SIZE: 512
      NORM_BY_NUM_EXAMPLES: False
      MATCH_HEIGHT: False
      BOX_CODER: ResidualCoder

    LOSS_CONFIG:
      LOSS_WEIGHTS: {
          'cls_weight': 1.0,
          'loc_weight': 2.0,
          'dir_weight': 0.2,
          'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      }

    DIM: 768
    BOX_CODE: ['xc', 'yc', 'zc', 'xl', 'yl', 'zl', 'cos', 'sin']

    POST_PROCESSING:
      RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
      SCORE_THRESH: 0.1
      OUTPUT_RAW_SCORE: False

      EVAL_METRIC: kitti

      NMS_CONFIG:
        MULTI_CLASSES_NMS: False
        NMS_TYPE: nms_gpu
        NMS_THRESH: 0.01
        NMS_PRE_MAXSIZE: 4096
        NMS_POST_MAXSIZE: 500

  ROI_HEAD:
### ----- Model ----- ###

### ----- Optimizer ----- ###
OPTIMIZER: # Training
  NAME: 'AdamW'

  LR: 0.001
  MIN_LR: 0.0001 # for scheduler
  BETAS: [0.9, 0.999]
  WEIGHT_DECAY: 0.01
  MOMENTUM: 0.9

  BATCH_SIZE: 4
  NUM_WORKERS: 0 # 0 for dataloader_error / 4 for batch 16

  MAX_EPOCH: 11
  
  SCHEDULER: 'CosineAnnealingLR' # in [None (empty), 'LambdaLR', 'CosineAnnealingLR']
  TYPE_TOTAL_ITER: 'every' # in ['every', 'all'] / every epoch
### ----- Optimizer ----- ###

### ----- Validation ----- ###
cfg_eval_ver2: True
VAL:
  IS_VALIDATE: True
  IS_CONSIDER_VAL_SUBSET: False
  VAL_PER_EPOCH_SUBSET: 1
  NUM_SUBSET: 500 # 500
  VAL_PER_EPOCH_FULL: 11 # epoch for validate full dataset

  LIST_VAL_CONF_THR: [0.0, 0.3]
  LIST_VAL_IOU: [0.7, 0.5, 0.3]
  # This is for logging, change the iou threshold in 'utils/kitti_eval'

  CLASS_VAL_KEYWORD: {
    'Sedan': 'sed',
    'Bus or Truck': 'bus',
    'Motorcycle': 'mot',
    'Bicycle': 'bic',
    'Bicycle Group': 'big',
    'Pedestrian': 'ped',
    'Pedestrian Group': 'peg'
  }

  REGARDING: 'anchor' # in ['anchor']
  LIST_CARE_VAL: ['Sedan', 'Bus or Truck']
### ----- Validation ----- ###

### ----- Visualization ----- ###
VIS:
  # OpenCV
  CLASS_BGR: {
    'Sedan': [0,255,0],
    'Bus or Truck': [0,50,255],
    'Motorcycle': [0,0,255],
    'Bicycle': [0,255,255],
    'Pedestrian': [255,0,0],
    'Pedestrian Group': [255,0,100],
    'Label': [128,128,128]
  }

  # Open3D
  CLASS_RGB: {
    'Sedan': [0, 1, 0],
    'Bus or Truck': [1, 0.2, 0],
    'Motorcycle': [1, 0, 0],
    'Bicycle': [1, 1, 0],
    'Pedestrian': [0, 0, 1],
    'Pedestrian Group': [0.4, 0, 1],
    'Label': [0.5, 0.5, 0.5]
  }
  
  ROI:
    TYPE: 'default' # ['default', 'cube']
    DEFAULT: [0,100,-40,40,-10,60] # x_min_max, y_min_max, z_min_max / Dim: [m]

  # For BEV model visualization
  Z_CENTER: {
    'Sedan': 0.5,
    'Bus or Truck': 1.5,
    'Motorcycle': 0.5,
    'Bicycle': 0.5,
    'Pedestrian': 0.5,
    'Pedestrian Group': 0.5,
  }

  # For BEV model visualization
  Z_HEIGHT: {
    'Sedan': 1.9,
    'Bus or Truck': 1.9,
    'Motorcycle': -1,
    'Bicycle': -1,
    'Pedestrian': 2,
    'Pedestrian Group': -1,
  }
### ----- Visualization ----- ###
